REM
REM General settings, please adjust to your needs!
REM 
set SRC_DRIVE=e:
set SRC_PATH=tmp\src
set DST_PATH=x:\bla\foo

set VSHADOW=vshadow.exe
set LN=ln.exe

REM Create a temporary name for the share, e.g. take the timestamp
REM 
for /f "delims=" %%a in ('%LN% --datetime') do set VSS_SHARE=%%a

REM call vshadow to create a persistent shadow
REM
%VSHADOW% -p -script=vss-setvar.cmd %SRC_DRIVE%

REM vss-setvar.cmd has been generated by vshadow.exe
REM
call vss-setvar.cmd

REM Create the temporary share, and specify a path relativ to %SRC_DRIVE 
REM via %SRC_PATH%. %VSS_SHARE% will then point to %SRC_DRIVE\%SRC_PATH%
REM
%VSHADOW% -er=%shadow_id_1%,"%VSS_SHARE%","%SRC_PATH%"

REM Run the intended copy job 
REM
%LN% --copy \\localhost\%VSS_SHARE% %DST_PATH%

REM Remove the shadow
REM
%VSHADOW% -ds=%shadow_id_1%
