REM
REM General settings, please adjust to your needs!
REM 
set SRC_DRIVE=e:
set SRC_PATH=tmp\src
set DST_PATH=x:\bla\foo

set VSHADOW=vshadow.exe
set LN=ln.exe

REM call vshadow to create a persistent shadow
REM
%VSHADOW% -p -script=vss-setvar.cmd %SRC_DRIVE%

REM vss-setvar.cmd has been generated by vshadow.exe
REM
call vss-setvar.cmd

REM Run the intended copy job 
REM
%LN% --copy %SHADOW_DEVICE_1%\%SRC_PATH% %DST_PATH%

REM Remove the shadow
REM
%VSHADOW% -ds=%SHADOW_ID_1%
