REM
REM General settings, please adjust to your needs!
REM 
set SRC_DRIVE=e:
set DST_PATH=x:\bla\foo

set VSHADOW=vshadow.exe
set LN=ln.exe

REM call vshadow to create a persistent shadow
REM
%VSHADOW% -p -script=vss-setvar.cmd %SRC_DRIVE%

REM vss-setvar.cmd has been generated by vshadow.exe
REM
call vss-setvar.cmd

REM Run the intended copy job 
REM
%LN% --backup --anchor %SRC_DRIVE%\ --mirror %SHADOW_DEVICE_1% %DST_PATH%

REM Remove the shadow
REM
%VSHADOW% -ds=%SHADOW_ID_1%
